name: Build iOS App

on: workflow_dispatch
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # Checkout the repo
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        architecture: x64
    # Generates package files
    - name: Generate package files
      shell: bash
      run: flutter pub get;flutter pub run build_runner build --delete-conflicting-outputs;
    # Generates example app files
    - name: Generate example app files
      shell: bash
      run: cd example;flutter pub get;flutter pub run build_runner build --delete-conflicting-outputs;
    # Build ios app
    - name: Delivering IPA
      shell: bash
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      # run: echo $PROJECT_ID
      run: flutter build ipa --dart-define='PROJECT_ID=$PROJECT_ID' --release;
    - name: Deploying with fastlane
      shell: bash
      run: cd ios;fastlane beta;