name: Build iOS App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # Checkout the repo
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        architecture: x64
    # Generates package files
    - shell: bash
      run: flutter pub get
    - shell: bash
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - shell: bash
      run: cd ios;pod install;
    # Generates ios files
    - shell: bash
      run: cd ..;cd example;
    - shell: bash
      run: flutter pub get
    - shell: bash
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - shell: bash
      run: cd ios;pod install;
    - shell: bash
      run: cd ..
    # Build ios app
    - shell: bash
      run: echo '########## 🍎🍎 Delivering IPA to TestFlight...'
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
    - shell: bash
      run: flutter build ipa --dart-define='PROJECT_ID=$PROJECT_ID' --release
    - shell: bash
      run: cd ios
    - shell: bash
      run: fastlane beta