name: Publish to pub.dev

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write
    runs-on: macos-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Install Flutter
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1

      # Get package dependencies and generate files
      - name: Get package dependencies and generate files
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      # Get example app dependencies and generate files
      - name: Get example app dependencies and generate files
        working-directory: example
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      # Publish
      - name: Check Publish Warnings
        run: flutter pub publish --dry-run
      # - name: Publish Package
      #   run: flutter pub publish -f